product_name: LayoutFreezer
version: 0.2.0

timestamp_format: "%Y-%m-%d_%H-%M-%S"
logger_config: "{root_dir}/logger.json"
#preferences_path: config/preferences.json
systray_icon: "{root_dir}/layoutfreezer.png"
#TODO: implement env vars replacements in config files
database_path: "~/.layoutfreezer/database"
