product_name: LayoutFreezer
version: 0.2.0

timestamp_format: "%Y-%m-%d_%H-%M-%S"
logger_config: "{root_dir}/logger.json"
systray_icon: "{root_dir}/layoutfreezer.png"
database_path: "~/.layoutfreezer/database"
preferences_path: "~/.layoutfreezer/prefs.yml"
preferences_default: "prefs.yml"
